In [1]:
import numpy as np

In [6]:
escalar = 5.679

vector = np.array(
    [3, 4, 5]
)

matriz = np.array(
    [
        [1, 2], 
        [3, 4], 
        [5, 6]
    ]
)

In [3]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [4]:
A = matriz.T + vector

In [5]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [7]:
C = matriz + 42

In [8]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [ ]:
# Broadcasting es extender una matriz o vector para que tenga la misma forma que otra matriz o vector

In [9]:
D = matriz + np.array([[42], [42], [42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


In [10]:
# Vector de 5 elementos
v = np.array([1, 2, 3, 4, 5])

# Matriz de 5x5
m = np.array(
    [
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]
    ]
)

# Broadcasting
r = m + v
print(r)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
