Matriz Identidad

$
Id = \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$


Otra matriz especial

Matriz Inversa

$A*A^{-1} = Id$

Matriz singular
$S -> \nexists S^{-1}$

In [1]:
import numpy as np

In [2]:
vector = np.array([1, 2, 3, 4, 5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


$$
\begin{pmatrix}
1 & 0 & 0 & 0 & 0 \\
0 & 2 & 0 & 0 & 0 \\
0 & 0 & 3 & 0 & 0 \\
0 & 0 & 0 & 4 & 0 \\
0 & 0 & 0 & 0 & 5 \\
\end{pmatrix}

\begin{pmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
x_5 \\
\end{pmatrix}
=
\begin{pmatrix}
1x_1 \\
2x_2 \\
3x_3 \\
4x_4 \\
5x_5 \\
\end{pmatrix}
$$

In [5]:
A = np.diag([2, 3, 4, 5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [11]:
v1 = np.array([[1,1,1,1]])
print(v1)
print("----------")
print(v1.T)
print("----------")
print(A.dot(v1.T))

[[1 1 1 1]]
----------
[[1]
 [1]
 [1]
 [1]]
----------
[[2]
 [3]
 [4]
 [5]]


$$
\begin{pmatrix}
1 & 0 & 0 & 0 & 0 \\
0 & 2 & 0 & 0 & 0 \\
0 & 0 & 3 & 0 & 0 \\
0 & 0 & 0 & 4 & 0 \\
0 & 0 & 0 & 0 & 5 \\
\end{pmatrix}

\begin{pmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
x_5 \\
\end{pmatrix}
=
\begin{pmatrix}
1x_1 \\
2x_2 \\
3x_3 \\
4x_4 \\
5x_5 \\
\end{pmatrix}
$$

$$A * A^{-1} = Id$$

Para calcular la inversa en este caso seria dividir por el elemento que estuve multiplicando.
Para recuperar $x_1$ seria dividir entre 1
Lo que quiero es recuperar $x_2$ lo que debo hacer es dividir $\frac{2x_2}{2}$ entonces calcular $A^{-1}$ seria poner en la diagonal 1 sobre cada uno de los elementos de la diagonal

In [12]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [13]:
Identidad = A.dot(A_inv)
print(Identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


Una matriz es simetrica cuando su transpuesta es igual a la matriz
$A = A^{T}$

In [15]:
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [16]:
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [19]:
simetrica = np.array(
                        [
                            [1, 2, 3], 
                            [2, -1, 7], 
                            [3, 7, 11]
                        ]
                    )

print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [18]:
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


$(AB)^{T} = B*A$