Una matriz es ortogonal cuando todas sus filas son mutuamente ortonormales y todas sus columnas son mutuamentes ortonormales, esto si pensamos a las filas y columnas como vectores, estariamos diciendo que v1, v2 y v3, tienen que ser mutuamente ortogonales.

$$
\begin{pmatrix}
\vec{v_1} 
\vec{v_2}
\vec{v_3}
\end{pmatrix}
$$

In [1]:
import numpy as np

In [2]:
matriz = np.array(
    [
        [1,0,0],
        [0,1,0],
        [0,0,1]
    ]
)

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


$$
\begin{pmatrix}
\vec{v_1} 
\vec{v_2}
\vec{v_3}
\end{pmatrix}
$$

$$
v_1 \text{ es ortogonal a } v_2
$$
$$
v_1 \text{ es ortogonal a } v_3
$$
$$
v_2 \text{ es ortogonal a } v_3
$$

In [ ]:
print(matriz[:,0].dot(matriz[:,1])) # v1.v2

0


In [ ]:
print(matriz[:,0].dot(matriz[:,2])) # v1.v3

0


In [ ]:
print(matriz[:,1].dot(matriz[:,2])) # v2.v3

0


In [6]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


Por lo anterior podemos decir que son ortonormales

In [7]:
# Primer fila y todos los elementos de su columna multiplicados por 
# la segunda fila y todos los elementos de su columna
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [8]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [9]:
# Por definición, la norma de un vector es la raíz cuadrada de la suma de los cuadrados de sus componentes
# La norma de un vector es un número no negativo que mide la longitud del vector
# La norma de un vector es cero si y solo si el vector es el vector cero

Una matriz ortogonal tiene la siguiente propiedad: 

$A^T * A = A * A^T = Id$

$A^T = A^{-1}$

In [10]:
A = np.array([[np.cos(100), -np.sin(100)], [np.sin(100), np.cos(100)]])

print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [11]:
print("Comprobar si es ortogonal")
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

Comprobar si es ortogonal
0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [12]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [13]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [14]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [15]:
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [16]:
print(1/A.dot(A_inv))

[[ 1. inf]
 [inf  1.]]


c:\Users\kevin\anaconda3\envs\Platzi-FundamentosAL\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
