In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = matriz * vector # Multiplicacion de matriz de 3x2 por vector de 2 devuelve matriz de 3x2

In [4]:
B = matriz.dot(vector) # Producto punto de matriz de 3x2 por vector de 2 devuelve vector de 3
'''
Tenemos la matriz de 3x2:
1 2
3 4
5 6

Y el vector de 2:
2
3

Para obtener el producto punto de la matriz por el vector, se multiplica cada fila de la matriz por el vector y se suman los resultados:
1*2 + 2*3 = 8
3*2 + 4*3 = 18
5*2 + 6*3 = 28
'''

In [5]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [6]:
print(B)

[ 8 18 28]


In [7]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]
