### Asociativa
$$A * (B * C) = (A * B) * C$$

### Distributiva
$$A * (B + C) = (A * B) + (A * C)$$

### Conmutativa
$$B * C = C * B$$

In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [3]:
# Asociativa
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [5]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [7]:
# Distributiva
D = A.dot(B+C)
E = A.dot(B) + A.dot(C)
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [8]:
print(D == E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [9]:
F = B.dot(C)
G = C.dot(B)
print(F == G)

[[False False]
 [False False]]


In [10]:
print(F)
print(G)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]


In [11]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [12]:
v1_tv2 = v1.T.dot(v2) # v1^T * v2
v2_tv1 = v2.T.dot(v1) # v2^T * v1
# Trnsponemos v1 y v2 para que se puedan multiplicar

In [13]:
print(v1_tv2)

[[41]]


In [14]:
print(v2_tv1)

[[41]]
