In [1]:
import numpy as np

In [2]:
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
vector = np.array(
    [
        [2],
        [3],
        [5],
        [7]
    ]
)

In [5]:
print(identidad.dot(vector))

[1. 2. 3. 4.]


In [9]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


El producto de un vector por una matriz identidad resulta en el mismo vector. Esto se debe a que la matriz identidad actúa como el elemento neutro en la multiplicación de matrices. 

Dado el vector:
$ \text{vector} = \begin{bmatrix} 2 \\ 3 \\ 5 \\ 7 \end{bmatrix} $

y la matriz identidad:
$ \text{identidad} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix} $

El producto de la matriz identidad por el vector es:
$ \text{identidad} \cdot \text{vector} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix} \cdot \begin{bmatrix} 2 \\ 3 \\ 5 \\ 7 \end{bmatrix} = \begin{bmatrix} 2 \\ 3 \\ 5 \\ 7 \end{bmatrix} $

Como se puede observar, el resultado es el mismo vector original.

In [10]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])

In [11]:
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [13]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


$A * A^{-1} = Identidad$

In [15]:
A.dot(inversa_A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
singular = np.array([[1,1],[1,1]])
print(singular)

[[1 1]
 [1 1]]


In [17]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix