In [2]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True)

$3x + y = 1$

$2x + y = 1$

Para escribir el sistema de ecuaciones en forma de matriz, podemos representarlo de la siguiente manera:

$
\begin{pmatrix}
3 & 1 \\
2 & 1
\end{pmatrix}
$
$
\begin{pmatrix}
x \\
y
\end{pmatrix} = 
\begin{pmatrix}
1 \\
1
\end{pmatrix}
$

$Ax = b$

In [4]:
A = np.array([[3,1], [2,1]])
print(A)

[[3 1]
 [2 1]]


In [6]:
b = np.array([[1], [1]])

In [7]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [8]:
x = inversa_A.dot(b)
print(x)

[[0.]
 [1.]]


$$Ax = b$$

$$A^{-1}Ax = A^{-1}b$$

$$x = A^{-1}b$$

In [9]:
A.dot(x) # Debe ser igual a b en este caso [1,1]

array([[1.],
       [1.]])

$3x + y = 3$

$2x + y = 7$

Para escribir el sistema de ecuaciones en forma de matriz, podemos representarlo de la siguiente manera:

$
\begin{pmatrix}
3 & 1 \\
2 & 1
\end{pmatrix}
$
$
\begin{pmatrix}
x \\
y
\end{pmatrix} = 
\begin{pmatrix}
3 \\
7
\end{pmatrix}
$

$Ax = b$

$
A =
\begin{pmatrix}
3 & 1 \\
2 & 1
\end{pmatrix}
$

$
x = 
\begin{pmatrix}
x \\
y
\end{pmatrix}
$

$
b = 
\begin{pmatrix}
3 \\
7
\end{pmatrix}
$

In [10]:
sol_2 = inversa_A.dot(np.array([[3], [7]]))
print(sol_2)

[[-4.]
 [15.]]


In [11]:
A.dot(sol_2) # Debe ser igual a [3,7] en este caso

array([[3.],
       [7.]])