In [2]:
import numpy as np

In [2]:
vector = np.array([1/2,1/2,1/2,1/2])
print(np.linalg.norm(vector))

1.0


In [3]:
matriz = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matriz.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [4]:
matriz = np.array([[1, 3], [5,6]])
print(matriz)

[[1 3]
 [5 6]]


In [5]:
print(matriz + 3)

[[4 6]
 [8 9]]


In [6]:
vector = np.array([-50,-25,0,25,100,-300])
print(np.linalg.norm(vector, ord=0)) # Estamos calculando la norma L0

5.0


In [ ]:
y1 = np.array([7,-1])
y2 = np.array([3,-1])

print(y1)
print(y2)

[7 2]
[3 5]


In [11]:
A = np.array([[7,-1],[3,-1]])
print(A)

[[ 7 -1]
 [ 3 -1]]


In [12]:
b = np.array([[-2],[-5]])
print(b)

[[-2]
 [-5]]


In [13]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.25 -0.25]
 [ 0.75 -1.75]]


In [14]:
x = A_inv.dot(b)
print(x)

[[0.75]
 [7.25]]


In [15]:
escalar = 3.1
print(escalar.shape)

AttributeError: 'float' object has no attribute 'shape'

In [17]:
vector = np.array([1, 2, 3, 4, 5])

matriz = np.diag(vector)

print(matriz)

print(np.linalg.det(matriz))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
119.99999999999997


**Ahora aprendiste:**
* Dominar conceptos de Algebra lineal como vetcores, Matrices, Tensores con Python
* Configurar el entorno de desarrollo con Anaconda y Python
* Ejecutar operaciones con matrices
* Resolver sistemas de ecuaciones con Python
* Calcular e interpretar el efecto del determinante en la transformacion del espacio